# -*- restclient -*-

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
#                         Login/Logout
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

# The API currently supports Basic Authentication as well as OAuth2.0 via
# Facebook. 
#
# For Basic Authentication, set the Authorization header as follows (using the
# user bob with password 'password') as per
# https://en.wikipedia.org/wiki/Basic_access_authentication:
#
# echo -n "bob:password" | base64 (yields Ym9iOnBhc3N3b3Jk)
# Authorization: Basic Ym9iOnBhc3N3b3Jk
#
# Note that the Basic Authentication mechanism provides no encrypting or
# hashing of the credentials, they are merely base64 encoded and therefore
# sent in the clear unless HTTPS is used
#
#
# The API also supports OAuth2.0, specifically Facebook's OAuth2.0 provider.
# Currently (Oct 2016) there are no plans for a Fanmobi web app, only native
# apps, and the 'Connect with Facebook/etc' functionality will live in the
# native code. Therefore, this API assumes the caller has already received
# a valid OAuth token and simply passes it as a parameter when making API
# calls.
#
# Proposed changes to login:
#
# 1. remove login via basic authentication
# 2. only support login via external service (facebook, Google, Twitter).
# 3. modify the /login/ endpoint to take a oauth_token (as before) but:
#           - make a request to a protected endpoint using the token to get
#             the user's 'friendly name' and unique id
#           - using the above info, generate a JWT and return to the caller
#           - caller now includes this JWT in subsequent api requests


:api-root = http://127.0.0.1:8000/api

:bob-login = Basic Ym9iOnBhc3N3b3Jk
:alice-login = Basic YWxpY2U6cGFzc3dvcmQ=
:admin-login = Basic YWRtaW46cGFzc3dvcmQ= 
:counting_crows-login = Basic Y291bnRpbmdfY3Jvd3M6cGFzc3dvcmQ=

:fanmobi-auth := :bob-login
:anonymous_id = bob

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
#    Login/Logout 
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

#
# Login
#
POST :api-root/login/
Content-Type: application/json

{
  "anonymous_id": ":anonymous_id"
}

#
# Logout
#
POST :api-root/logout/

# Login via Facebook auth token
POST :api-root/login/
Content-Type: application/json

{
  "fb_access_token": ""
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
#    Genre 
#
#    Only Admins can create, edit, or delete genres at this time
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

#
# Get all genres 
# 
GET :api-root/genre/
Accept: application/json
Authorization: :fanmobi-auth 

#
# Get specific genres 
# 
GET :api-root/genre/1/
Accept: application/json
Authorization: :fanmobi-auth 

#
# Update existing genre 
# 
PUT :api-root/genre/1/
Accept: application/json
Content-Type: application/json
Authorization: :fanmobi-auth 

{
  "name": "Alternative"
}

#
# Create a new genre 
# 
POST :api-root/genre/
Accept: application/json
Content-Type: application/json
Authorization: :fanmobi-auth 

{
  "name": "Hippie Music"
}

#
# Delete a new genre 
# 
DELETE :api-root/genre/6/
Accept: application/json
Authorization: :fanmobi-auth 


# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
#    Group 
#
#    Only accessible via admins. These are very static - don't worry about
#    creating endpoints to add, edit, or delete them
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

#
# Get all groups 
# 
GET :api-root/group/
Accept: application/json
Authorization: :fanmobi-auth 


# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
#    Profile 
#
#    This is the basic 'user'-like table for all Fanmobi users, whether they
#    are fans, artists, or admins. 
#
#    current_latitude and current_longitude are in Decimal Degrees
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

#
# Get all profiles 
#
#  Only admins can get all profiles
# 
GET :api-root/profile/
Accept: application/json
Authorization: :fanmobi-auth 

#
# Get my profile 
#
# 
GET :api-root/profile/1/
Accept: application/json
Authorization: :fanmobi-auth 

#
# Update my profile
#
# TODO: this works to update a user's avatar, but the location data doesn't
#       stick - it always gets set to null after this call
#
PUT :api-root/profile/1/
Accept: application/json
Content-Type: application/json
Authorization: :fanmobi-auth 

{
  "current_latitude": "39.2904",
  "current_longitude": "-76.6122",
  "avatar": {
    "id": 3
  }
}

#
# Get all unread messages for this user
#
GET :api-root/profile/4/message/
Accept: application/json
Authorization: :fanmobi-auth 

#
# Mark a message as read for a user
#
DELETE :api-root/profile/4/message/1/
Accept: application/json
Authorization: :fanmobi-auth 

#
# Get all artists this user follows
#
GET :api-root/profile/4/connected/
Accept: application/json
Authorization: :fanmobi-auth 

#
# Disconnect from an artist
#
DELETE :api-root/profile/4/connected/1/
Accept: application/json
Authorization: :fanmobi-auth 

#
# Connect to an artist
#
PUT :api-root/profile/4/connected/1/
Accept: application/json
Authorization: :fanmobi-auth 



# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
#                         Artists 
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

#
# Get all artists 
# 
GET :api-root/artist/
Accept: application/json
Authorization: :fanmobi-auth 

#
# Create a new Artist 
#
# Must reference an existing user
# 
POST :api-root/artist/
Content-Type: application/json
Authorization: :fanmobi-auth 

{
  "basic_profile": {
    "user": {
      "username": "someguy"
    }
  },
  "name": "someGuysBand"
}

#
# Get my artist profile
#
GET :api-root/artist/1/
Accept: application/json
Authorization: :fanmobi-auth 

#
# Update my artist profile
#
# Note that both basic_profile.user.username and name are required. Also,
# the username provided must match that of the currently logged in user
#
# TODO: update of Avatar or Icon is not supported here yet
#
PUT :api-root/artist/1/
Accept: application/json
Content-Type: application/json
Authorization: :fanmobi-auth 

{
  "basic_profile": {
    "user": {
      "username": "counting_crows"
    },
    "current_latitude": "39.2904",
    "current_longitude": "-76.6122"
  },
  "name": "counting_crows",
  "genres": [
    {
      "name": "Alternative"
    }
  ],
  "hometown": "Baltimore"
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
#    Shows
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

#
# Get shows for artist
#
GET :api-root/artist/1/show/
Accept: application/json
Authorization: :fanmobi-auth 

#
# Add a show for this artist
#
# Times are in format: 2015-09-19T00:00:00Z (YYYY-MM-DDTHH:MM:SSZ)
#
POST :api-root/artist/1/show/
Accept: application/json
Content-Type: application/json
Authorization: :fanmobi-auth 

{
  "start": "2016-12-24T20:00Z",
  "end": "2016-12-25T00:00Z",
  "latitude": "38.918229",
  "longitude": "-77.023795",
  "venue_name": "9:30 Club"
}

#
# Edit an existing show
#
# TODO: doesn't seem to be a way to do this yet

#
# Delete an existing show
#
# TODO: can't do this w/o getting the pk (id) back 


# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
#    Messages
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

#
# Get all messages for an artist
#
GET :api-root/artist/1/message/
Accept: application/json
Authorization: :fanmobi-auth 

#
# Create a message for an artist
#
POST :api-root/artist/1/message/
Accept: application/json
Content-Type: application/json
Authorization: :fanmobi-auth 

{
  "text": "Hello fans from the CCs!"
}

#
# Delete a message from an artist
#

DELETE :api-root/artist/1/message/2/
Accept: application/json
Authorization: :fanmobi-auth 


# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
#    Connections
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

#
# Get all users connected to an artist
#

GET :api-root/artist/1/connected/
Accept: application/json
Authorization: :fanmobi-auth 

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
#    Artists-in-Radius
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

#
# Get artists with a radius (km) of given coordinates (Decimal Degrees)
#
:radius = 150
# coordinates for Philadelphia (counting crows were put in Baltimore)
:latitude = 39.9526
:longitude = -75.1652

GET :api-root/artists-in-radius/?radius=:radius&latitude=:latitude&longitude=:longitude
Accept: application/json
Authorization: :fanmobi-auth 


# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
#    Image 
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

#
# Get all images
#
GET :api-root/image/
Accept: application/json
Authorization: :fanmobi-auth 

#
# Upload an image
#
#  This won't work from Emacs restclient. Use something like Postman to test
#
#  form data:
#       image_type = avatar|icon
#       file_extension = jpg|png
#       image = <FILE>
#
POST :api-root/image/
Accept: application/json
Content-Type: multipart/form-data
Authorization: :fanmobi-auth 

image_type=avatar
image=<FILE>
file_extension=jpeg

#
# Get an image
#
# This does technically work from Emacs restclient but is better done in
# a tool like Postman
#
GET :api-root/image/3/
Authorization: :fanmobi-auth 

#
# Delete an image
#
# TODO: this does not actually delete the image from the disk
#
DELETE :api-root/image/3/
Authorization: :fanmobi-auth 