---
- name: Update apt cache
  apt:
    update_cache: yes
  become: true

- name: Install dependencies
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python-httplib2 # required to use uri module in ansible
    - python-selinux # required for ansible
    - git
    - vim
    - libjpeg-dev
    - libfreetype6-dev
    - zlib1g-dev
  become: true

- name: Create fanmobi user
  user:
    name: fanmobi
    comment: "fanmobi"
    # group: fanmobi
    password: "password"
  become: true

- name: Creates .ssh directory for fanmobi user
  file: path=/home/fanmobi/.ssh state=directory
  become: true
  become_user: fanmobi

# This public key is set on Github repo Settings under "Deploy keys"
- name: Upload the private key used for Github cloning
  copy: src={{ github_private_key }} dest=/home/fanmobi/.ssh/{{ github_private_key }}
  become: true
  become_user: fanmobi

- name: Correct SSH deploy key permissions
  file: dest=/home/fanmobi/.ssh/{{ github_private_key }} mode=0600
  become: true
  become_user: fanmobi

- name: Create /usr/local/fanmobi directory
  file:
    path: /usr/local/fanmobi
    owner: fanmobi
    mode: 0755
    recurse: true
    state: directory
  become: true

- name: Create download directory
  file:
    path: "{{ download_dir }}"
    owner: fanmobi
    state: directory
  become: true
